bIo9/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import password_reset_confirm
from .views import register, index, log_in, log_out, change_password, reset_password, set_new_password,\
					show_user_page, change_user_photo, change_user_info, post_a_blog, like_a_blog,\
					follow_a_user, unfollow_a_user, make_a_comment, get_full_chat
from . import views

app_name = 'bIo9'

urlpatterns = [
	url(r'^$', index, name='index'),
	#authentication
	url(r'^register/$', register, name='register'),
	url(r'^login/$', log_in, name='login'),
	url(r'^logout/$', log_out, name='logout'),
	url(r'^change_password/$', change_password, name="change_password"),
	url(r'^reset_password/$', reset_password, name="reset_password"),
	url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, {'post_reset_redirect': 'bIo9:set_new_password', 'template_name': 'bIo9/set_new_password.html'}, name="password_reset_confirm"),
	url(r'^reset_password/set_new_password$', set_new_password, name='set_new_password'),
	#user
	url(r'^user/user_id=(?P<user_id>[1-9]+[0-9]*)/$', show_user_page, name='show_user_page'),
	url(r'^user/change_photo$', change_user_photo, name='change_user_photo'),
	url(r'^user/change_info$', change_user_info, name='change_user_info'),
	url(r'^user/post_a_blog$', post_a_blog, name='post_a_blog'),
	url(r'^user/like_a_blog$', like_a_blog, name='like_a_blog'),
	url(r'^user/follow_a_user$', follow_a_user, name='follow_a_user'),
	url(r'^user/unfollow_a_user$', unfollow_a_user, name='unfollow_a_user'),
	url(r'^user/comment/blog_id=(?P<blog_id>[1-9]+[0-9]*)$', make_a_comment, name='make_a_comment'),
	url(r'^user/comment/comment_id=(?P<comment_id>[1-9]+[0-9]*)$', get_full_chat, name='get_full_chat'),
	url(r'^notifications/$', views.NotificationListView.as_view(), name='notifications'),
	url(r'^notification-list/$', views.NotificationListApiView.as_view({'get':'list'}), name='notification-list'),
	url(r'^notification-list/count$', views.NotificationListApiView.as_view({'get':'count'}), name='notification-count'),
	url(r'^notification/(?P<pk>[1-9]+[0-9]*)$', views.NotificationUpdateApiView.as_view({'get':'retrieve', 'PUT':'update', 'patch':'partial_update'}), name='notification'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bIo9/', include('bIo9.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bIo9/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
import re
import os

sex_choices = (('F', 'Female'),
				('M', 'Male'),
				('S', 'Secret'))

def validate_nickname(nickname):
	pattern = re.compile(r'^[a-zA-Z]+[a-zA-Z0-9]*$')
	if re.match(pattern, nickname):
		return True
	else:
		return False

def upload_to(instance, filename):
	return os.path.join(str(instance.id), filename)

class User(AbstractUser):
	sex = models.CharField(choices=sex_choices, max_length=10, default='S')
	nickname = models.CharField(max_length=10, validators=((validate_nickname,)))
	age = models.PositiveIntegerField(default=17)
	mood = models.TextField(blank=True)
	introduction = models.TextField(blank=True)
	photo = models.ImageField(upload_to=upload_to, default='dragonCat.jpg')
	follows = models.TextField(blank=True, default='')

	class Meta(AbstractUser.Meta):
		pass


class Blog(models.Model):
	content = models.TextField(blank=True)
	update_time = models.DateTimeField(auto_now=True)
	followers = models.TextField(blank=True)
	followers_amt = models.PositiveIntegerField(default=0)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def can_be_followed_by(self, user_id):
		return not int(user_id) in (int(x) for x in self.followers.split(';') if x != '') and int(user_id) != self.user.id


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	content = models.TextField(blank=True)
	reply_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
	create_time = models.DateTimeField(auto_now=True)
	my_floor = models.PositiveIntegerField(default=1)


class Notification(models.Model):
	'''
	used for notifications of follow and unfollow and comment on blog or another comment
	'''
	note_sub = models.ForeignKey(User, on_delete=models.CASCADE, related_name='note_sub')
	note_verb = models.CharField(max_length=100, default='followed')
	note_obj = models.ForeignKey(User, on_delete=models.CASCADE, related_name='note_obj')
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE, blank=True, null=True)
	comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=True, null=True)
	create_time = models.DateTimeField(auto_now=True)
	has_read = models.BooleanField(default=False)
     
	class Meta:
		ordering = ['-create_time']

bIo9/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.forms import ModelForm, Textarea, HiddenInput
from .models import User, Blog


class RegisterForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User


class LoginForm(AuthenticationForm):
	class Meta:
		model = User


class ChangePasswordForm(PasswordChangeForm):
	class Meta:
		model = User


class ResetPasswordForm(PasswordResetForm):
	class Meta:
		model = User

	def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='bIo9/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
		super(ResetPasswordForm, self).save(domain_override=domain_override,
             subject_template_name=subject_template_name,
             email_template_name=email_template_name,
             use_https=use_https, token_generator=token_generator,
             from_email=from_email, request=request, html_email_template_name=html_email_template_name,
             extra_email_context=extra_email_context)


class PasswordSetForm(SetPasswordForm):
	class Meta:
		model = User


class ChangePhotoForm(ModelForm):
	class Meta:
		model = User
		fields = ('photo',)


class ChangeInfoForm(ModelForm):
	class Meta:
		model = User
		fields = ('nickname', 'age', 'sex', 'email', 'mood', 'introduction')
		widgets = {
		'mood': Textarea(attrs={'rows': 1}),
		'introduction': Textarea(attrs={'rows': 2})
		}

class PostBlogForm(ModelForm):
	class Meta:
		model = Blog
		fields = ('content',)
		widgets = {
		'content': Textarea(attrs={'rows': 2, 'placeholder': 'blog content ...', 'required': 'required'}),
		}

bIo9/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.http import HttpResponse
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User, Blog, Comment, Notification
from .forms import RegisterForm, LoginForm, ChangePasswordForm, ResetPasswordForm, PasswordSetForm,\
					ChangePhotoForm, ChangeInfoForm, PostBlogForm
from .utils import get_cur_page, mark_notification_as_read
# Create your views here.
import re
import json

from .notifications import follow_sig, unfollow_sig, comment_sig
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.decorators import detail_route
from rest_framework import renderers
from rest_framework.response import Response
from .serializers import NotificationSerializer

def register(request):
	redirect_to = request.POST.get('next', request.GET.get('next', ''))
	title = 'register'
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			form.instance.nickname = form.cleaned_data['username']
			form.save()
			login(request, form.instance)
			messages.success(request, 'Welcome to the bIo9 world.')
			if redirect_to:
				return redirect(redirect_to)
			else:
				return redirect(reverse('bIo9:show_user_page', kwargs={'user_id': request.user.id}))
		else:
			return render(request, 'bIo9/register.html', {'form': form, 'title': title})
	else:
		form = RegisterForm()
		return render(request, 'bIo9/register.html', {'form': form, 'title': title})


def index(request):
	blogs = Blog.objects.order_by('-update_time')
	blogs_per_page = 3
	cur_page_no = request.GET.get('page', 1)
	cur_page = get_cur_page(blogs, blogs_per_page, cur_page_no)

	active_users = User.objects.order_by('-last_login')[0:12]
	return render(request, 'bIo9/index.html', {'title': 'index',
												'cur_page': cur_page,
												'users': active_users})


def log_in(request):
	redirect_to = request.POST.get('next', request.GET.get('next', ''))
	title = 'log in'
	if request.method == 'POST':
		form = LoginForm(data=request.POST)
		# import pdb;pdb.set_trace()
		if form.is_valid():
			login(request, form.user_cache)
			messages.success(request, 'You have logged in succesfully.')
			if redirect_to:
				return redirect(redirect_to)
			else:
				return redirect(reverse('bIo9:show_user_page', kwargs={'user_id': request.user.id}))
		else:
			messages.error(request, 'Log in failed.')
			return render(request, 'bIo9/login.html', {'form': form, 'title': title})
	else:
		form = LoginForm()
		return render(request, 'bIo9/login.html', {'form': form, 'title': title, 'next': redirect_to})


@login_required
def log_out(request):
	# import pdb;pdb.set_trace()
	logout(request)
	messages.success(request, 'You have succesfully logged out.')
	redirect_to = request.POST.get('next', request.GET.get('next', ''))
	if redirect_to:
		return redirect(redirect_to)
	else:
		return redirect(reverse('bIo9:index'))
	return redirect('/')


#changing password would logout, let user choose whether to log automatically.
@login_required
def change_password(request):
	title = 'change password'
	if request.method == 'POST':
		form = ChangePasswordForm(request.user, request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'password succesfully changed.')
			return redirect(reverse('bIo9:index'))
		else:
			messages.error(request, 'change password failed.')
			return render(request, 'bIo9/change_password.html', {'form': form, 'title': title})
	else:
		form = ChangePasswordForm(request.user)
		return render(request, 'bIo9/change_password.html', {'form': form, 'title': title})


@login_required
def reset_password(request):
	email = request.user.email
	if email == '':
		messages.error(request, "You don't have an email, Please set your email first.")
		return redirect(reverse('bIo9:index'))
	title = 'reset password'
	if request.method == 'POST':
		form = ResetPasswordForm(request.POST)
		if form.is_valid():
			if email == form.cleaned_data['email']:
				form.save(request=request)
				return render(request, 'bIo9/email_sent.html')
			else:
				form.add_error('email', 'the email input does not match your email.')
				return render(request, 'bIo9/reset_password.html', {'form': form, 'title': title})	
		else:
			return render(request, 'bIo9/reset_password.html', {'form': form, 'title': title})
	else:
		form = ResetPasswordForm()
		return render(request, 'bIo9/reset_password.html', {'form': form, 'title': title})


@login_required
@require_POST
def set_new_password(request):
	form = PasswordSetForm(request.user, request.POST)
	if form.is_valid():
		form.save()
		messages.success(request, 'Password succesfully reset.Please log in again.')
		return redirect(reverse('bIo9:index'))
	else:
		messages.error(request, 'Password reset failed.')
		return render(request, 'bIo9/set_new_password.html', {'form': form, 'title': 'set new password'})	


def show_user_page(request, user_id):
	title = 'user page'
	user = get_object_or_404(User, id=user_id)
	blogs = user.blog_set.order_by('-update_time')
	blogs_per_page = 2
	cur_page_no = request.GET.get('page', 1)
	cur_page = get_cur_page(blogs, blogs_per_page, cur_page_no)

	request_user = request.user
	can_follow_user = True
	if request_user.is_authenticated:
		my_follows = request_user.follows.split(';')  
		if str(user.id) in my_follows:
			can_follow_user = False
	else:
		can_follow_user = False

	user_follow_ids = user.follows.split(';')
	user_follows = [ get_object_or_404(User, id=int(x)) for x in user_follow_ids if x != '']
	mark_notification_as_read(request)
	return render(request, 'bIo9/user_page.html', {'cur_user': user, 
													'title': title, 
													'cur_page': cur_page,
													'can_follow_user': can_follow_user,
													'user_follows': user_follows})


@login_required
def change_user_photo(request):
	title = 'change user photo'
	if request.method == 'POST':
		form = ChangePhotoForm(request.POST, request.FILES)
		if request.FILES and form.is_valid():
			photo = form.cleaned_data['photo']
			user = request.user
			if re.match(r'^/media/[1-9]+[0-9]*/.+$', user.photo.url):
				user.photo.delete()
			user.photo = photo
			user.save()
			messages.success(request, 'photo succesfully upload')
			return redirect(reverse('bIo9:show_user_page', kwargs={'user_id': user.id}))
		else:
			if not request.FILES:
				messages.error(request, 'Please choose a file.')
			else:
				messages.error(request, 'upload photo failed')
			return render(request, 'bIo9/change_photo.html', {'form': form, 'title': title})
	else:
		form = ChangePhotoForm()
		return render(request, 'bIo9/change_photo.html', {'form': form, 'title': title})

@login_required
def change_user_info(request):
	cur_user = request.user
	title = 'change user information'
	if request.method == 'POST':
		form = ChangeInfoForm(request.POST)
		if form.is_valid():
			cur_user.nickname = form.cleaned_data['nickname']
			cur_user.age = form.cleaned_data['age']
			cur_user.sex = form.cleaned_data['sex']
			cur_user.email = form.cleaned_data['email']
			cur_user.mood = form.cleaned_data['mood']
			cur_user.introduction = form.cleaned_data['introduction']
			cur_user.save()
			messages.success(request, 'Change Information Done.')
			return redirect(reverse('bIo9:change_user_info'))
		else:
			messages.error(request, 'Change Information Failed.')
			return render(request, 'bIo9/change_user_info.html', {'form': form, 'title': title})
	else:
		form = ChangeInfoForm(cur_user._wrapped.__dict__)
		return render(request, 'bIo9/change_user_info.html', {'form': form, 'title': title})


@login_required
def post_a_blog(request):
	title = 'post a blog'
	if request.method == 'POST':
		form = PostBlogForm(request.POST)
		if form.is_valid():
			request.user.blog_set.create(content=form.cleaned_data['content'])
			return redirect(reverse('bIo9:show_user_page', kwargs={'user_id': request.user.id}))
		else:
			return render(request, 'bIo9/post_a_blog.html', {'form': form, 'title': title})
	else:
		form = PostBlogForm()
		return render(request, 'bIo9/post_a_blog.html', {'form': form, 'title': title})


@login_required
@require_POST
def like_a_blog(request):
	ret_data = {}
	blog_id = int(request.POST['ele_id'].split('_')[-1])
	blog = get_object_or_404(Blog, id=blog_id)
	user_id = request.POST['user_id']
	blog.followers += user_id + ';'
	blog.followers_amt += 1
	blog.save()
	ret_data['result'] = 'success'
	ret_data['new_val'] = blog.followers_amt
	return HttpResponse(json.dumps(ret_data))


@login_required
@require_POST
def follow_a_user(request):
	ret_data = {}
	user = request.user
	followee_id = request.POST['page_user_id']
	user.follows += followee_id + ';'
	user.save()
	ret_data['result'] = 'success'	
	follow_sig.send(user.__class__, follower=user.id, followee=followee_id)
	return HttpResponse(json.dumps(ret_data))

@login_required
@require_POST
def unfollow_a_user(request):
	ret_data = {}
	user = request.user
	follows_list = user.follows.split(';')
	followee_id = request.POST['page_user_id']
	follows_list.remove(followee_id)
	user.follows = ';'.join(follows_list) if len(follows_list) != 0 else ''
	user.save()
	ret_data['result'] = 'success'
	unfollow_sig.send(user.__class__, follower=user.id, followee=followee_id)
	return HttpResponse(json.dumps(ret_data))

class NotificationListView(LoginRequiredMixin, ListView):
	model = Notification
	context_object_name = 'notifications'
	template_name = 'bIo9/notification_list.html'
	login_url = reverse_lazy('bIo9:login')

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(note_obj=self.request.user)


def make_a_comment(request, blog_id):
	title = 'comment'

bIo9/templates/bIo9/__blogs_in_one_page.html
{% load template_tags %}

{% for obj in cur_page %}
	<div class='one_blog'>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 one_comment_reply_to">
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="thumbnail tiny_photo"><img src="{{ obj.user.photo.url }}" class="photo_in_thumbnail"></a>
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="reply_user">{{ obj.user.nickname }}</a>
			</div>
			<div class="post_time col-lg-6 col-md-6 col-sm-6">post time  {{ obj.update_time|date:"Y-m-d H:i:s" }}</div>
		</div>
		<p class="blog_content">{{ obj.content }}</p>
		<div class="row comment_and_follow_row">
			<div class="col-lg-2 col-md-2 col-sm-2">
				{% if user.is_authenticated and obj|blog_can_be_followed:user.id %}
					<a href="javascript:void(0);" id="blog_{{ obj.id }}" onclick="like_a_blog(this)">
						<i class="fa fa-thumbs-o-up fa-lg mythumb"></i>
					</a>
				{% else %}
					<i class="fa fa-thumbs-up fa-lg mythumb"></i>
				{% endif %}
					<span>{{ obj.followers_amt }}</span>	 		
		 	</div>
		 	<div class="col-lg-2 col-md-2 col-sm-2">
		 		<a class="btn btn-reverse" href="{% url 'bIo9:make_a_comment' obj.id %}"><i class="fa fa-comment"></i> <strong>Comment({{ obj.comment_set.count }})</strong></a>
		 	</div>
		</div>
	</div>
{% endfor %}

<div class="pagination">
	{% if cur_page.has_previous %}
		<a href="?page={{ cur_page.previous_page_number }}">previous</a>
	{% endif %}
		{{ cur_page.number}}
	{% if cur_page.has_next %}
		<a href="?page={{ cur_page.next_page_number }}">next</a>
	{% endif %}
</div>

<script type="text/javascript">
	function like_a_blog(obj){
	$.ajax({
		url: "{% url 'bIo9:like_a_blog' %}",
		type: "POST",
		data: {csrfmiddlewaretoken: '{{ csrf_token }}', 
				'user_id': '{{ user.id }}',
				'ele_id': $(obj).attr('id')},
		success: function(ret_data){
			$(obj).next().text(jQuery.parseJSON(ret_data)['new_val']);
			$(obj).children().attr('class', 'fa fa-thumbs-up fa-lg mythumb')
			$(obj).parent().prepend($(obj).children())
			$(obj).remove();
		}
	});
};
</script>

bIo9/templates/bIo9/change_password.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>Log In</strong></h2>
			<form action="{% url 'bIo9:change_password' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary pull-right" id="btn_register">register</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/layout.html
<html>
<head>
	<title>
		{% if title %}
			{{ title }}
		{% else %}
			bIo9
		{% endif %}
	</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/myjs.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/my_functions.js' %}"></script>
</head>
<body>	
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a href="{% url 'bIo9:index' %}" class="navbar-brand" id="brand">bIo9</a>
			</div>
			<ul class="nav navbar-nav pull-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'bIo9:show_user_page' user.id %}?next={{ request.path }}" class="thumbnail" id="nav_photo_outline">
						<img src="{{ user.photo.url }}" class="img-responsive" id="nav_photo">
					</a></li>
					<li><a href="{% url 'bIo9:notifications' %}">
						Notifications<span class="notification-count"></span>
					</a></li>
					<li><a href="{% url 'bIo9:change_password' %}?next={{ request.path }}">Change Password</a></li>
					<li><a href="{% url 'bIo9:reset_password' %}?next={{ request.path }}">Reset Password</a></li>
					<li><a href="{% url 'bIo9:logout' %}?next={{ request.path }}">Log Out</a></li>
				{% else %}
					<li><a href="{% url 'bIo9:register' %}?next={{ request.path }}">Register</a></li>
					<li><a href="{% url 'bIo9:login' %}?next={{ request.path }}">Log In</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
	{% if messages %}
		<div class="messages" id="message_box">
			{% for message in messages %}
				<li {% if message.tags %} class="message {{ message.tags }}-message" {% endif %}>{{ message }}</li>
			{% endfor%}
		</div>
	{% endif %}
	<div class="main_area">
		{% block body %}
		{% endblock %}
	</div>
</body>
<script>
	$(document).ready(function(){
		$.ajax({
			url: "{% url 'bIo9:notification-count' %}",
			type: "get",
			cache: false,
			data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
			success: function(ret_data) {
				$(".notification-count").text(ret_data['count']);
			}
		});
	});
</script>
</html>

bIo9/templates/bIo9/user_page.html
{% extends 'bIo9/layout.html' %}



{% block body %}
<!-- include some information -->
<div id="user_page_head" class="container">
	<div class="row">
		<div id="user_photo" class="col-lg-3 col-md-3 col-sm-3">
			{% if cur_user == user %}
				<a class="thumbnail user_photo_outline" href="{% url 'bIo9:change_user_photo' %}">
					<img src="{{ cur_user.photo.url }}" alt="user photo" class="user_photo">
				</a>
			{% else %}
				<a href="javascript:void(0);" class="thumbnail user_photo_outline" disabled>
					<img src="{{ cur_user.photo.url }}" alt="user photo" class="user_photo">
				</a>
			{% endif %}
		</div>
		<div id="user_info_area" class="col-lg-9 col-md-9 col-sm-9">
			<div class="row user_info_row">
				<div class="col-lg-4 col-md-4 col-sm-4"><label class="user_info_item">nickname:</label> {{cur_user.nickname}}</div>
				<div class="col-lg-2 col-md-2 col-sm-2"><label class="user_info_item">age:</label> {{cur_user.age}}</div>
				<div class="col-lg-2 col-md-2 col-sm-2">
					<label class="user_info_item">sex:</label> 
					{% if cur_user.sex == 'M' %}
						<i class="fa fa-mars"></i>
					{% elif cur_user.sex == 'F' %}
						<i class="fa fa-venus"></i>
					{% else %}
						<i class="fa fa-genderless"></i>
					{% endif %}
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4"><label class="user_info_item">email:</label> {{cur_user.email}}</div>
			</div>
			<div class="user_info_row">
				<label class="user_info_item">feelings:</label> {{cur_user.mood}}
			</div>
			<div class="user_info_row">
				<label class="user_info_item">introduction:</label> {{cur_user.introduction}}
			</div>
			{% if cur_user == user %}
				<div class="user_info_row">
					<a href="{% url 'bIo9:change_user_info' %}" class="btn btn-default">Change My Information</a>
				</div>
				<div class="user_info_row">
					<a href="{% url 'bIo9:post_a_blog' %}" class="btn btn-default">Post A Blog</a>
				</div>
			{% elif cur_user != user and user.is_authenticated %}
				<div class="user_info_row">
					<button class="btn btn-default" onclick="follow_a_user(this)">
						{% if can_follow_user %}Follow{%else%}Unfollow{% endif %}
					</button>
				</div>
			{% endif %}
		</div>
	</div>
</div>
<!-- include blogs and relations -->
<div class="container">
	<div class="rows">
		<div class="col-lg-9 col-md-9 col-sm-8 col-xs-10" id="blog_display_area">
			<h2 class="text-center">My Blogs:</h2>
			<hr>
			{% include 'bIo9/__blogs_in_one_page.html' %}
		</div>

		<div class="col-lg-3 col-md-3 col-sm-4 col-xs-2">
			<h2 class="text-center">My Follows:</h2>
			<hr>
			{% for user in user_follows %}
				<a href="{% url 'bIo9:show_user_page' user.id %}" class="thumbnail active_user_outline">
					<img src="{{ user.photo.url }}" class="active_user_photo">
					<p class="user_nickname">{{ user.nickname }}</p>
				</a>
			{% endfor %}
		</div>
	</div>
</div>
<script type="text/javascript">
	function follow_a_user(obj){
		if($.trim($(obj).text()) == $.trim("Follow")){
			var url = "{% url 'bIo9:follow_a_user' %}";
			var btn_text = 'Unfollow';
		}else{
			var url = "{% url 'bIo9:unfollow_a_user' %}";
			var btn_text = 'Follow';
		}
		$.ajax({
			url: url,
			cache: false,
			type: "POST",
			data: {csrfmiddlewaretoken: '{{ csrf_token }}', 'page_user_id': '{{ cur_user.id }}'},
			success: function(ret_data){
				$(obj).text(btn_text);
			}
		});
	};
</script>
{% endblock %}